# On publication of a release, trigger workflow dispatch events in other repositories
name: Published Release
# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.TOKEN }}
jobs:
  # Trigger creation of the wheelhouse
  trigger-wheelhouse-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger FLAMEGPU2-wheelhouse
        env:
          REPO: "ptheywood/FLAMEGPU2-wheelhouse"
          WORKFLOW: "ci.yml"
        run: |
          gh workflow run ${WORKFLOW} -R ${REPO}
          sleep 5
          gh run watch -R ${REPO} $(gh run list -R ${REPO} -w ${WORKFLOW} -L1 --json databaseId --jq .[0].databaseId)
